server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/farmer/**, /api/dealer/**, /api/admin/**, /api/users/**
          filters:
            - name: AuthFilter
              args:
                excludedPaths: /api/auth/login,/api/auth/register

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - AuthFilter

        - id: deal-service
          uri: lb://deal-service
          predicates:
            - Path=/api/deals/**
          filters:
            - AuthFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - AuthFilter

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - AuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: c8109a2fbc6ae1f2021b386ae059c6b3aae889befce992bc1050e32250eff0f9

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.cropdeal: DEBUG
    root: INFO