server.port=8085
spring.application.name=payment-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone={EUREKA_URL}
eureka.instance.prefer-ip-address=true

stripe.secret.key=${STRIPE_SECRET}
stripe.currency=${STRIPE_CURRENCY}
stripe.success.url=${STRIPE_SUCCESS}
stripe.cancel.url=${STRIPE_FAIL}

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

management.endpoints.web.exposure.include=health,info
managment.endpoints.health.show-details=never