server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

management.endpoints.web.exposure.include=health,info
managment.endpoints.health.show-details=never